apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: projectx-claims
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: projectx-claims
  targetCPUUtilizationPercentage: 50
